[unix_http_server]
file=/tmp/supervisord.sock
username=kozo
password=kozo

[inet_http_server]
port=127.0.0.1:9001
username=kozo
password=kozo

[supervisord]
logfile=%(here)s/supervisord.log
logfileMaxbytes=50MB
logfileBackups=10
pidfile=%(here)s/supervisord.pid
identifier=supervisor

[program:prerun]
command=/home/kozo/codes/supervisord/run_mpi.sh
process_name=%(program_name)s_%(process_num)02d
numprocs=4
autostart=true
startsecs=3
startretries=3
autorestart=true
exitcodes=0,2
stopsignal=TERM
stopwaitsecs=10
stopasgroup=true
killasgroup=true
user=kozo
redirect_stderr=false
stdout_logfile=AUTO
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stdout_capture_maxbytes=0
stdout_events_enabled=true
stderr_logfile=AUTO
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
stderr_capture_maxbytes=0
stderr_events_enabled=false
envFiles=global.env
directory=/tmp
serverurl=AUTO

[program:run]
command=/home/kozo/codes/supervisord/run_mpi_hello.sh
process_name=%(program_name)s_%(process_num)02d
numprocs=4
depends_on=prerun
autostart=true
autorestart=true
priority=200

[supervisorctl]
serverurl=http://127.0.0.1:9001
