[inet_http_server]
nodename = node-2
port = 127.0.0.1:9001
remotes = node-1:127.0.0.1:9002

[program:test-1]
#directory = /c/Users/stou/supervisord/src/github.com
command = python hello.py --port 5000

[program:test-2]
#directory = /c/Users/stou/supervisord/src/gitgub.com
command = python hello.py --port 5001

[program:test-3]
command = ./env-test.py
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[group:test-group]
programs = test-1,test-2,test-3
