[supervisord]
logfile = /tmp/supervisord.log
logfile_maxbytes = 50MB
logfile_backups=1
loglevel = info
pidfile = /tmp/supervisord.pid
nodaemon = false
minfds = 1024
minprocs = 200
umask = 022
;user = chrism
identifier = supervisor
directory = /tmp
nocleanup = true
childlogdir = /tmp
strip_ansi = false
environment = KEY1="value1",KEY2="value2"

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[inet_http_server]
nodename = node-2
port = 127.0.0.1:9001
;remote_1_node = node-1
remote_1_port = 127.0.0.1:9002
remote_1_user = test
remote_1_password = test

[program:test-1]
#directory = /c/Users/stou/supervisord/src/github.com
command = python3 hello.py --port 5000
stdout_logfile = test-1-stdout.log
stderr_logfile = test-1-stderr.log
stdout_logfile_maxbytes = 1MB
stderr_logfile_maxbytes = 1MB
stdout_logfile_backups = 1
stderr_logfile_backups = 1

[program:test-2]
#directory = /c/Users/stou/supervisord/src/gitgub.com
command = python3 hello.py --port 5001

[program:test-3]
#directory = /c/Users/stou/supervisord/src/github.com
command = python3 hello.py --port 5002
stdout_logfile = test-3-stdout.log
stderr_logfile = test-3-stderr.log
stdout_logfile_maxbytes = 1MB
stderr_logfile_maxbytes = 1MB
stdout_logfile_backups = 1
stderr_logfile_backups = 1


[program:test-4]
#directory = /c/Users/stou/supervisord/src/github.com
command = python3 hello.py --port 5003
stdout_logfile = test-4-stdout.log
stderr_logfile = test-4-stderr.log
stdout_logfile_maxbytes = 1MB
stderr_logfile_maxbytes = 1MB
stdout_logfile_backups = 1
stderr_logfile_backups = 1




[program:echo]
command = python3 echo.py
stdout_logfile = echo-stdout.log
stderr_logfile = echo-stderr.log
stdout_logfile_maxbytes = 1MB
stderr_logfile_maxbytes = 1MB
stdout_logfile_backups = 1
stderr_logfile_backups = 1

[group:test-group]
programs = test-1,test-2
